# Generated by Django 4.2 on 2023-05-08 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0005_remove_usuario_numero_seguridad_persona_cargo_and_more'),
        ('inmuebles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tasa', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, null=True)),
                ('titular', models.CharField(max_length=20, null=True)),
                ('rif', models.CharField(max_length=10, null=True)),
                ('banco', models.CharField(choices=[('0102 - BANCO DE VENEZUELA', '0102 - BANCO DE VENEZUELA'), ('0104 - VENEZOLANO DE CRÉDITO', '0104 - VENEZOLANO DE CRÉDITO'), ('0105 - BANCO MERCANTIL', '0105 - BANCO MERCANTIL'), ('0108 - BANCO PROVINCIAL', '0108 - BANCO PROVINCIAL'), ('0114 - BANCO DEL CARIBE', '0114 - BANCO DEL CARIBE'), ('0115 - BANCO EXTERIOR', '0115 - BANCO EXTERIOR'), ('0128 - BANCO CARONÍ', '0128 - BANCO CARONÍ'), ('0134 - BANESCO', '0134 - BANESCO'), ('0137 - SOFITASA', '0137 - SOFITASA'), ('0138 - BANCO PLAZA', '0138 - BANCO PLAZA'), ('0151 - FONDO COMÚN', '0151 - FONDO COMÚN'), ('0156 - 100% BANCO', '0156 - 100% BANCO'), ('0157 - BANCO DEL SUR', '0157 - BANCO DEL SUR'), ('0163 - BANCO DEL TESORO', '0163 - BANCO DEL TESORO'), ('0166 - BANCO AGRÍCOLA', '0166 - BANCO AGRÍCOLA'), ('0168 - BANCRECER', '0168 - BANCRECER'), ('0169 - MIBANCO', '0169 - MIBANCO'), ('0171 - BANCO ACTIVO', '0171 - BANCO ACTIVO'), ('0172 - BANCAMIGA', '0172 - BANCAMIGA'), ('0174 - BANPLUS', '0174 - BANPLUS'), ('0175 - BANCO BICENTENARIO', '0175 - BANCO BICENTENARIO'), ('0177 - BANFAN', '0177 - BANFAN'), ('0191 - BANCO NACIONAL DE CRÉDITO', '0191 - BANCO NACIONAL DE CRÉDITO')], max_length=50)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('comentario', models.TextField()),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('R', 'Rechazado'), ('A', 'Aprobado')], max_length=1)),
                ('comentario_cajero', models.TextField()),
                ('referencia', models.IntegerField()),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmuebles.compra')),
                ('emisora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_emisora', to='pagos.cuenta')),
                ('receptora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_receptora', to='pagos.cuenta')),
                ('tasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.cambio')),
            ],
        ),
    ]
