# Generated by Django 4.2 on 2023-05-10 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='rif',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='titular',
        ),
    ]
