# Generated by Django 4.2 on 2023-05-10 18:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_remove_cuenta_rif_remove_cuenta_titular'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 5, 10, 14, 57, 44, 575536)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pago',
            name='tasa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pagos.cambio'),
        ),
    ]
