# Generated by Django 4.2 on 2023-05-29 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_pago_fecha_alter_pago_tasa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pago',
            old_name='receptora',
            new_name='cuenta',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='emisora',
        ),
    ]
