# Generated by Django 4.2 on 2023-05-29 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_rename_receptora_pago_cuenta_remove_pago_emisora'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='fecha_transaccion',
            field=models.DateField(default=datetime.datetime(2023, 5, 29, 14, 0, 9, 665230)),
            preserve_default=False,
        ),
    ]
