# Generated by Django 4.2 on 2023-07-17 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0005_alter_inmueble_estado'),
        ('pagos', '0005_pago_fecha_transaccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='inmuebles.compra'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='referencia',
            field=models.CharField(max_length=15),
        ),
    ]
