# Generated by Django 4.2 on 2023-05-04 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0005_remove_usuario_numero_seguridad_persona_cargo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('R', 'En Revisión'), ('A', 'Activo'), ('D', 'Denegado'), ('E', 'Revisión por Edición'), ('C', 'Revisión para Cancelación')], default='R', max_length=1)),
                ('ano_construccion', models.IntegerField()),
                ('tipo_construccion', models.CharField(choices=[('Casa Individual', 'Casa Individual'), ('Casa Dúplex', 'Casa Dúplex'), ('Casa Triplex', 'Casa Triplex'), ('Casa de Villa', 'Casa de Villa'), ('Apartamento Regular', 'Apartamento Regular'), ('Apartamento PentHouse', 'Apartamento PentHouse')], default='Casa Individual', max_length=45)),
                ('tiene_estacionamiento', models.BooleanField()),
                ('tamano', models.DecimalField(decimal_places=2, max_digits=10)),
                ('habitaciones', models.IntegerField()),
                ('banos', models.IntegerField()),
                ('amueblado', models.BooleanField()),
                ('descripcion', models.TextField()),
                ('comentarios_internos', models.TextField()),
                ('ubicacion_detallada', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agente', to='usuarios.persona')),
                ('dueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dueno', to='usuarios.persona')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmuebles.sector')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('P', 'Primera Cita'), ('E', 'Espera de Pago'), ('C', 'Por Cancelación'), ('X', 'Cancelada'), ('S', 'Segunda Cita'), ('F', 'Finalizada')], max_length=1)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.persona')),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmuebles.inmueble')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignada', models.DateTimeField()),
                ('estado', models.CharField(choices=[('E', 'En Espera'), ('C', 'Cancelada'), ('P', 'Pendiente por Resultado'), ('F', 'Finalizada')], max_length=1)),
                ('resultados', models.TextField()),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmuebles.compra')),
            ],
        ),
    ]
