# Generated by Django 4.2 on 2023-05-14 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='sector',
            name='parroquia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inmuebles.parroquia'),
            preserve_default=False,
        ),
    ]
