# Generated by Django 4.2 on 2023-07-05 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuario_persona'),
        ('inmuebles', '0002_parroquia_sector_parroquia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='inmueble',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inmuebles.inmueble'),
        ),
        migrations.AddField(
            model_name='cita',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.persona'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='compra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inmuebles.compra'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('E', 'Espera de Pago'), ('C', 'Por Cancelación'), ('X', 'Cancelada'), ('S', 'Cita de Formalidades'), ('F', 'Finalizada')], max_length=1),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='comentarios_internos',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='estado',
            field=models.CharField(choices=[('R', 'En Revisión'), ('A', 'Activo'), ('D', 'Denegado'), ('E', 'Revisión por Edición'), ('C', 'Revisión para Cancelación'), ('X', 'Cancelado')], default='R', max_length=1),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='tipo_construccion',
            field=models.CharField(choices=[('Casa Individual', 'Casa Individual'), ('Casa Dúplex', 'Casa Dúplex'), ('Casa Tríplex', 'Casa Tríplex'), ('Casa de Villa', 'Casa de Villa'), ('Apartamento Regular', 'Apartamento Regular'), ('Apartamento PentHouse', 'Apartamento PentHouse')], default='Casa Individual', max_length=45),
        ),
    ]
