# Generated by Django 4.2 on 2023-07-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0003_cita_inmueble_cita_persona_alter_cita_compra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='tiene_estacionamiento',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='agua',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inmueble',
            name='aseo',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inmueble',
            name='electricidad',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inmueble',
            name='estacionamientos',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inmueble',
            name='gas',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inmueble',
            name='internet',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inmueble',
            name='pisos',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('E', 'En Espera'), ('C', 'Cancelada'), ('P', 'Pendiente por Resultado'), ('F', 'Finalizada - Visto Bueno'), ('X', 'Finalizada - Visto Malo')], default='E', max_length=1),
        ),
        migrations.AlterField(
            model_name='cita',
            name='resultados',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('E', 'Espera de Pago'), ('C', 'Por Cancelación'), ('X', 'Cancelada'), ('S', 'Cita de Formalidades'), ('F', 'Finalizada')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='estado',
            field=models.CharField(choices=[('R', 'En Revisión'), ('A', 'Activo'), ('T', 'Compromiso de Compra'), ('D', 'Denegado'), ('E', 'Revisión por Edición'), ('C', 'Revisión para Cancelación'), ('X', 'Cancelado')], default='R', max_length=1),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='tipo_construccion',
            field=models.CharField(choices=[('Casa Individual', 'Casa Individual'), ('Casa Dúplex', 'Casa Dúplex'), ('Casa Tríplex', 'Casa Tríplex'), ('Casa de Villa', 'Casa de Villa'), ('Apartamento Regular', 'Apartamento Regular'), ('Apartamento PentHouse', 'Apartamento PentHouse'), ('Terreno', 'Terreno')], default='Casa Individual', max_length=45),
        ),
    ]
