# Generated by Django 4.2 on 2023-07-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0004_remove_inmueble_tiene_estacionamiento_inmueble_agua_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='estado',
            field=models.CharField(choices=[('R', 'En Revisión'), ('A', 'Activo'), ('T', 'Compromiso de Compra'), ('D', 'Denegado'), ('E', 'Revisión por Edición'), ('C', 'Revisión para Cancelación'), ('X', 'Cancelado'), ('S', 'Formalidades Pendientes'), ('V', 'Vendida')], default='R', max_length=1),
        ),
    ]
