# Generated by Django 4.2 on 2023-08-14 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0005_alter_inmueble_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='compra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='inmuebles.compra'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='tipo_construccion',
            field=models.CharField(choices=[('Casa Individual', 'Casa Individual'), ('Casa Dúplex', 'Casa Dúplex'), ('Casa Tríplex', 'Casa Tríplex'), ('Casa de Villa', 'Casa de Villa'), ('Apartamento Regular', 'Apartamento Regular'), ('Apartamento PentHouse', 'Apartamento PentHouse'), ('Terreno', 'Terreno'), ('Oficina', 'Oficina'), ('Edificio', 'Edificio')], default='Casa Individual', max_length=45),
        ),
        migrations.CreateModel(
            name='Edicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('R', 'En Revisión'), ('A', 'Activo'), ('T', 'Compromiso de Compra'), ('D', 'Denegado'), ('E', 'Revisión por Edición'), ('C', 'Revisión para Cancelación'), ('X', 'Cancelado'), ('S', 'Formalidades Pendientes'), ('V', 'Vendida')], default='R', max_length=1)),
                ('ano_construccion', models.IntegerField()),
                ('tipo_construccion', models.CharField(choices=[('Casa Individual', 'Casa Individual'), ('Casa Dúplex', 'Casa Dúplex'), ('Casa Tríplex', 'Casa Tríplex'), ('Casa de Villa', 'Casa de Villa'), ('Apartamento Regular', 'Apartamento Regular'), ('Apartamento PentHouse', 'Apartamento PentHouse'), ('Terreno', 'Terreno'), ('Oficina', 'Oficina'), ('Edificio', 'Edificio')], default='Casa Individual', max_length=45)),
                ('estacionamientos', models.IntegerField()),
                ('tamano', models.DecimalField(decimal_places=2, max_digits=10)),
                ('habitaciones', models.IntegerField()),
                ('banos', models.IntegerField()),
                ('amueblado', models.BooleanField()),
                ('descripcion', models.TextField()),
                ('comentarios_internos', models.TextField(default='')),
                ('ubicacion_detallada', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pisos', models.IntegerField()),
                ('agua', models.BooleanField()),
                ('electricidad', models.BooleanField()),
                ('internet', models.BooleanField()),
                ('gas', models.BooleanField()),
                ('aseo', models.BooleanField()),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmuebles.inmueble')),
            ],
        ),
    ]
