# Generated by Django 4.2 on 2023-08-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0006_alter_cita_compra_alter_inmueble_tipo_construccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('E', 'En Espera'), ('C', 'Cancelada'), ('P', 'Pendiente por Resultado'), ('F', 'Finalizada - Visto Bueno Para Compra'), ('X', 'Finalizada - No Habilitado para Compra')], default='E', max_length=1),
        ),
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('E', 'Espera de Pago'), ('C', 'Por Cancelación'), ('X', 'Cancelada'), ('S', 'Cita de Formalidades'), ('F', 'Finalizada')], default='E', max_length=1),
        ),
    ]
