# Generated by Django 4.2 on 2023-04-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('V', 'V'), ('E', 'E'), ('J', 'J'), ('G', 'G')], max_length=1)),
                ('identificacion', models.CharField(max_length=9)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('puede_ver', models.BooleanField(default=False)),
            ],
        ),
    ]
