# Generated by Django 4.2 on 2023-04-07 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='persona',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.persona'),
        ),
    ]
