# Generated by Django 4.2 on 2023-04-30 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_usuario_correo_electronico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='numero_seguridad',
        ),
        migrations.AddField(
            model_name='persona',
            name='cargo',
            field=models.CharField(choices=[('A', 'Administrador'), ('G', 'Agente Inmobiliario'), ('C', 'Comprador')], default='C', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='numero_telefono',
            field=models.CharField(default='04121273360', max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.persona'),
        ),
    ]
